name: Build MicroPython

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MicroPython
        uses: actions/checkout@v3
        with:
          repository: micropython/micropython
          path: micropython
          submodules: recursive

      - name: Checkout MicroPython ulab
        uses: actions/checkout@v3
        with:
          repository: v923z/micropython-ulab
          path: ulab
          submodules: recursive

      - name: Checkout MicroPython ESP32-S3 N32R8
        uses: actions/checkout@v3
        with:
          path: MicroPython-ESP32-S3-N32R8

      - name: Copy ESP32_S3_N32R8 to micropython/ports/esp32/boards
        run: cp -r MicroPython-ESP32-S3-N32R8/ESP32_S3_N32R8 micropython/ports/esp32/boards
        
      - name: Install esp-idf
        run: |
          sudo apt update
          sudo apt install -y git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
          mkdir ~/esp
          cd ~/esp
          wget https://dl.espressif.com/github_assets/espressif/esp-idf/releases/download/v5.2.2/esp-idf-v5.2.2.zip
          unzip -q esp-idf-v5.2.2.zip && mv esp-idf-v5.2.2 esp-idf
          rm -f esp-idf-v5.2.2.zip
          cd ~/esp/esp-idf
          ./install.sh esp32s3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config

      - name: Build
        run: |
          export BUILD_DIR=$(pwd)

          cd $BUILD_DIR/micropython
          make -C mpy-cross
          
          cd $BUILD_DIR/micropython/ports/esp32
          source ~/esp/esp-idf/export.sh
          export IDF_TARGET=esp32s3
          make submodules
          make BOARD=ESP32_S3_N32R8 BOARD_VARIANT=SPIRAM_OCT USER_C_MODULES=$BUILD_DIR/ulab/code

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            micropython/ports/esp32/build-ESP32_S3_N32R8-SPIRAM_OCT/firmware.bin
            micropython/ports/esp32/build-ESP32_S3_N32R8-SPIRAM_OCT/bootloader/bootloader*
            micropython/ports/esp32/build-ESP32_S3_N32R8-SPIRAM_OCT/partition_table
            micropython/ports/esp32/build-ESP32_S3_N32R8-SPIRAM_OCT/*flash*
            micropython/ports/esp32/build-ESP32_S3_N32R8-SPIRAM_OCT/micropython*
